# Generated by Django 2.2.17 on 2020-12-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=128, verbose_name='消息'),
        ),
    ]
